#!/bin/bash
clear
cat <<'EOF'
    __    _   _            __            
   / /_  (_) (_)___ ______/ /_____  _____
  / __ \/ / / / __ `/ ___/ //_/ _ \/ ___/
 / / / / / / / /_/ / /__/ ,< /  __/ /    
/_/ /_/_/_/ /\__,_/\___/_/|_|\___/_/     
       /___/                             

git: ShubhamVis98/hijacker
EOF

installed_path=/usr/lib/hijacker
cd $installed_path
sudo -E python3 hijacker.py
